version: "3.7"

services:

  flask:
    build: ./flask
    container_name: silverball-flask
    restart: always
    environment:
      - APP_NAME=app
    expose:
      - 8081

  nginx:
    build: ./nginx
    container_name: silverball-nginx
    restart: always
    ports:
      - "80:80"
